import type { Metadata } from 'next';

import { inter, roboto, luckiest } from '../src/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${roboto.variable} ${luckiest.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
